[package]
name = "meteoraid"
version = "0.1.0"
authors = ["Thomas Daniels"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlua = "0.16.3"
clap = "2.33.0"
phf = { version = "0.8", features = ["macros"] }
